version: "3"

tasks:
  run:
    desc: Run doorpix
    silent: true
    cmds:
      - cmd: |
          export $(cat .env | xargs) &> /dev/null
          go run ./cmd/doorpix/main.go

  build:
    desc: "Build the project"
    cmds:
      - go build -o doorpix cmd/doorpix/main.go

  test:
    desc: "Run tests"
    cmds:
      - go test ./...
