
services:
  doorpix:
    image: ghcr.io/dieklingel/doorpix:main
    ports:
      - 8080:8080
    volumes:
      - ./doorpix.yaml:/var/doorpix/doorpix.yaml:ro
      - ${XDG_RUNTIME_DIR}/pipewire-0:/run/user/1000/pipewire-0
    environment:
      XDG_RUNTIME_DIR: /run/user/1000
    group_add:
      - ${AUDIO_GROUP_ID:-29}
      - ${VIDEO_GROUP_ID:-44}
      - ${GPIO_GROUP_ID:-986}
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/video0:/dev/video0
    env_file:
      - .env
