// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KioskDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Specification string                 `protobuf:"bytes,1,opt,name=specification,proto3" json:"specification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KioskDefinitionResponse) Reset() {
	*x = KioskDefinitionResponse{}
	mi := &file_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KioskDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KioskDefinitionResponse) ProtoMessage() {}

func (x *KioskDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KioskDefinitionResponse.ProtoReflect.Descriptor instead.
func (*KioskDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{0}
}

func (x *KioskDefinitionResponse) GetSpecification() string {
	if x != nil {
		return x.Specification
	}
	return ""
}

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventPath     string                 `protobuf:"bytes,1,opt,name=eventPath,proto3" json:"eventPath,omitempty"`
	EventData     map[string]string      `protobuf:"bytes,2,rep,name=eventData,proto3" json:"eventData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{1}
}

func (x *EmitRequest) GetEventPath() string {
	if x != nil {
		return x.EventPath
	}
	return ""
}

func (x *EmitRequest) GetEventData() map[string]string {
	if x != nil {
		return x.EventData
	}
	return nil
}

type ListenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventPath     string                 `protobuf:"bytes,1,opt,name=eventPath,proto3" json:"eventPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{2}
}

func (x *ListenRequest) GetEventPath() string {
	if x != nil {
		return x.EventPath
	}
	return ""
}

type ListenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventPath     string                 `protobuf:"bytes,1,opt,name=eventPath,proto3" json:"eventPath,omitempty"`
	EventData     map[string]string      `protobuf:"bytes,2,rep,name=eventData,proto3" json:"eventData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenResponse) Reset() {
	*x = ListenResponse{}
	mi := &file_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse) ProtoMessage() {}

func (x *ListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return file_core_proto_rawDescGZIP(), []int{3}
}

func (x *ListenResponse) GetEventPath() string {
	if x != nil {
		return x.EventPath
	}
	return ""
}

func (x *ListenResponse) GetEventData() map[string]string {
	if x != nil {
		return x.EventData
	}
	return nil
}

var File_core_proto protoreflect.FileDescriptor

const file_core_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"core.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x17KioskDefinitionResponse\x12$\n" +
	"\rspecification\x18\x01 \x01(\tR\rspecification\"\xa4\x01\n" +
	"\vEmitRequest\x12\x1c\n" +
	"\teventPath\x18\x01 \x01(\tR\teventPath\x129\n" +
	"\teventData\x18\x02 \x03(\v2\x1b.EmitRequest.EventDataEntryR\teventData\x1a<\n" +
	"\x0eEventDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\rListenRequest\x12\x1c\n" +
	"\teventPath\x18\x01 \x01(\tR\teventPath\"\xaa\x01\n" +
	"\x0eListenResponse\x12\x1c\n" +
	"\teventPath\x18\x01 \x01(\tR\teventPath\x12<\n" +
	"\teventData\x18\x02 \x03(\v2\x1e.ListenResponse.EventDataEntryR\teventData\x1a<\n" +
	"\x0eEventDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xaf\x01\n" +
	"\x04Core\x12H\n" +
	"\x12GetKioskDefinition\x12\x16.google.protobuf.Empty\x1a\x18.KioskDefinitionResponse\"\x00\x12.\n" +
	"\x04Emit\x12\f.EmitRequest\x1a\x16.google.protobuf.Empty\"\x00\x12-\n" +
	"\x06Listen\x12\x0e.ListenRequest\x1a\x0f.ListenResponse\"\x000\x01B3Z1github.com/dieklingel/doorpix/core/internal/protob\x06proto3"

var (
	file_core_proto_rawDescOnce sync.Once
	file_core_proto_rawDescData []byte
)

func file_core_proto_rawDescGZIP() []byte {
	file_core_proto_rawDescOnce.Do(func() {
		file_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)))
	})
	return file_core_proto_rawDescData
}

var file_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_proto_goTypes = []any{
	(*KioskDefinitionResponse)(nil), // 0: KioskDefinitionResponse
	(*EmitRequest)(nil),             // 1: EmitRequest
	(*ListenRequest)(nil),           // 2: ListenRequest
	(*ListenResponse)(nil),          // 3: ListenResponse
	nil,                             // 4: EmitRequest.EventDataEntry
	nil,                             // 5: ListenResponse.EventDataEntry
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_core_proto_depIdxs = []int32{
	4, // 0: EmitRequest.eventData:type_name -> EmitRequest.EventDataEntry
	5, // 1: ListenResponse.eventData:type_name -> ListenResponse.EventDataEntry
	6, // 2: Core.GetKioskDefinition:input_type -> google.protobuf.Empty
	1, // 3: Core.Emit:input_type -> EmitRequest
	2, // 4: Core.Listen:input_type -> ListenRequest
	0, // 5: Core.GetKioskDefinition:output_type -> KioskDefinitionResponse
	6, // 6: Core.Emit:output_type -> google.protobuf.Empty
	3, // 7: Core.Listen:output_type -> ListenResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_proto_init() }
func file_core_proto_init() {
	if File_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_proto_rawDesc), len(file_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_proto_goTypes,
		DependencyIndexes: file_core_proto_depIdxs,
		MessageInfos:      file_core_proto_msgTypes,
	}.Build()
	File_core_proto = out.File
	file_core_proto_goTypes = nil
	file_core_proto_depIdxs = nil
}
