#ifndef __PJ_CONFIG_SITE_H__
#define __PJ_CONFIG_SITE_H__

#define PJ_ICE_MAX_CAND 32
#define PJ_ICE_MAX_CHECKS (PJ_ICE_MAX_CAND * 16)
#define PJSIP_MAX_PKT_LEN 12288

#define PJMEDIA_HAS_VIDEO 1

#endif /* __PJ_CONFIG_SITE_H__ */
