version: '3'

tasks:
  generate:
    desc: Generate the project
    cmds:
      - export PATH="$PATH:$(go env GOPATH)/bin"
      - go generate ./...
  build:
    desc: Build the project
    cmds:
      - go build -o core cmd/main.go
  test:
    desc: Run tests
    cmds:
      - go test ./...
  containerize:
    desc: Build the container image
    cmds:
      - docker buildx build --platform linux/arm64 -t ghcr.io/dieklingel/doorpix/core:latest .
