version: '3'

tasks:
  generate:
    desc: Generate the project
    cmds:
      - export PATH=$PATH:$HOME/.pub-cache/bin:$(dirname -- $(which flutter-elinux))/../flutter/bin
      - mkdir -p lib/proto
      - protoc --dart_out=grpc:lib/proto -I ../protobuf core.proto
  build:
    desc: Build the project
    cmds:
      - flutter-elinux build elinux
  containerize:
    desc: Build the container image
    cmds:
      - docker buildx build --platform linux/arm64 -t ghcr.io/dieklingel/doorpix/kiosk:latest .
