name: Build and publish core image
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish-core-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: core
          platforms: linux/amd64,linux/arm64
          push: true
          tags: dieklingel/doorpix/core:latest
